//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stokEkstresi.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STI> STI { get; set; }
        public virtual DbSet<STK> STK { get; set; }
    
        public virtual ObjectResult<b_Result> b(string malKodu, Nullable<System.DateTime> baslangic, Nullable<System.DateTime> bitis)
        {
            var malKoduParameter = malKodu != null ?
                new ObjectParameter("malKodu", malKodu) :
                new ObjectParameter("malKodu", typeof(string));
    
            var baslangicParameter = baslangic.HasValue ?
                new ObjectParameter("baslangic", baslangic) :
                new ObjectParameter("baslangic", typeof(System.DateTime));
    
            var bitisParameter = bitis.HasValue ?
                new ObjectParameter("bitis", bitis) :
                new ObjectParameter("bitis", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<b_Result>("b", malKoduParameter, baslangicParameter, bitisParameter);
        }
    }
}
